<!-- Script Action File -->
<!-- For actions usage description see documentation -->

<ScriptActions>
	<SetDialogNodeEnabled/>
	<Disintegrate/>
	<InfluenceAbility/>
	<InfluenceSkill/>
	<InfluenceState/>
	<Info/>
	<InfoGUI/>
	<LeadToMap/>
	<GiveItem/>
	<AnimateTrigger/>
	<TranslateGameObject/>
	<ChangeCondition/>
	<PlacePickable/>
	<ParticleEffect/>
	<StaticToPickable/>
  <AddLight/>
</ScriptActions>